chore: rely on logs to stop jobs

diff --git a/.github/actions/run-test-kubernetes/action.yaml b/.github/actions/run-test-kubernetes/action.yaml
--- a/.github/actions/run-test-kubernetes/action.yaml
+++ b/.github/actions/run-test-kubernetes/action.yaml
@@ -164,26 +164,18 @@ runs:
         stern --output raw --selector job-name=$job -c metrics-exporter > metrics-exporter.log &
         stern --output raw --selector job-name=$job -c ${{ inputs.consensus }}-beacon > consensus.log &
         stern --output raw --selector job-name=$job -c ${{ inputs.execution }} > execution.log &
-        stern --selector job-name=$job &
         echo "Log watchers created";
         kubectl get job $job -o yaml  > jobspec.yaml;
+        stern --selector job-name=$job &
         #sleep 15;
         #kubectl describe pod $(kubectl get pods  -l job-name=$job --no-headers -o custom-columns=":metadata.name") > pod.yaml;
         #cat pod.yaml;
-    - name: Wait for test to finish or fail
-      shell: bash
-      run: |
-        export PATH=$HOME/bin:$PATH;
-        # Credit: https://stackoverflow.com/a/60286538
-        # wait for completion as background process - capture PID
-        kubectl wait --for=condition=complete  --timeout=2885m job/$(cat job.txt) &
-        completion_pid=$!
 
-        # wait for failure as background process - capture PID
-        kubectl wait --for=condition=failed --timeout=2885m job/$(cat job.txt) && exit 1 &
-        failure_pid=$!
-
-        # capture exit code of the first subprocess to exit
+        # Watch the coordinator logs until it says the test is successful or not.
+        ( tail -f -n0 coordinator.log & ) | grep -q "test completed!" &
+        completion_pid=$!;
+        ( tail -f -n0 coordinator.log & ) | grep -q "test failed!" && exit 1 &
+        failure_pid=$!;
         wait -n $completion_pid $failure_pid;
 
         # store exit code in variable
